### ISSUE TITLE
Send stamp for testing

### ISSUE THREAD

**Issue by gigiesposito** [supix/openkonnect#4]
hi guys, I don't want to be offtopic but I saw that there are people here who know how to use kronotech devices. My question is simple, we are trying to send remote clocks for testing. do you know how they can be sent and how to set the device to receive them? we use a KP-06N

**Comment by supix** [comment]
The code does contain the data pattern to send in order for the device to update the local clock. More precisely, take a look at [this method](https://github.com/supix/openkonnect/blob/de1837be34b94173f2161dbafdb30ed1ca22cff4/OpenKonnect/ProtocolloLettore/Concrete/LettoreKronotech.cs#L292). Cheers.

**Comment by gigiesposito** [comment]
@supix thank you. instead how can i send remote stamp for the same reason (test) ?

**Comment by supix** [comment]
OpenKonnect has this very objective: fetching stamps from Kronotech readers. The [same file](https://github.com/supix/openkonnect/blob/master/OpenKonnect/ProtocolloLettore/Concrete/LettoreKronotech.cs) linked above contains all the possible tasks OpenKonnect can accomplish. In the [GetTimbratura method](https://github.com/supix/openkonnect/blob/de1837be34b94173f2161dbafdb30ed1ca22cff4/OpenKonnect/ProtocolloLettore/Concrete/LettoreKronotech.cs#L111) you can find the data pattern to use to fetch a stamp from a reader.

**Comment by gigiesposito** [comment]
amazing! but i only saw to download clockings from the device. on the other hand, if I want to send a stamping to the device as if I were using the badge?

**Comment by gigiesposito** [comment]
amazing! but I only saw to download clockings from the device. on the other hand, if I want to send a stamping to the device as if I were using the badge?

**Comment by supix** [comment]
This is not possible. Stamps can be stored just by putting the card close to the reader.
